# Generated by Django 4.1.1 on 2022-11-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0011_categorytype_category_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytype',
            name='last_modified',
        ),
    ]
